# Generated by Django 5.1 on 2024-09-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='---------', max_length=9)),
                ('player_turn', models.CharField(default='X', max_length=1)),
                ('game_status', models.CharField(default='ongoing', max_length=10)),
            ],
        ),
    ]
